name: Test Dart Globe Action

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using Dart Globe
        uses: mastersam07/dart-globe-action@v0.21.1
        with:
          globe-token: ${{ secrets.GLOBE_TOKEN }}
          project-id: ${{ secrets.GLOBE_PROJECT_ID }}
          org-id: ${{ secrets.GLOBE_ORG_ID }}
