name: Test Dart Globe Action

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using Dart Globe
        uses: mastersam07/dart-globe-action@v0.21
        with:
          entrypoint: build/bin/server.dart
          globe-token: ${{ secrets.GLOBE_TOKEN }}
          project-id: polls_api-7efe
          org-id: a3253ac5-6748-4abc-8fee-78018dc770a1
